name: Full CI/CD Pipeline

on:
  push:
    branches: [main]

env:
  IMAGE_TAG: x7m7s7/devops:latest

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: pip install requests bandit jq

      - name: Install Gitleaks & Semgrep
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_$(uname -s)_$(uname -m).tar.gz | tar -xz -C /usr/local/bin gitleaks
          pip install semgrep

      - name: Run SAST (Bandit with B104 exclusion)
        run: |
          bandit -r app.py -f json -o bandit_output.json || true
          jq '.results | map(select(.test_id != "B104" and .issue_severity != "LOW"))' bandit_output.json > sast_results.json

      - name: Run Gitleaks
        run: gitleaks detect --source . --report-format json --report-path secrets_found.json || true

      - name: Run Semgrep
        run: semgrep --config auto . --json > semgrep_output.json || true

      - name: Merge all results
        run: |
          echo "{" > full_report.json
          echo '"sast":' >> full_report.json && (cat sast_results.json || echo '[]') >> full_report.json
          echo ',' >> full_report.json
          echo '"sca":' >> full_report.json && (cat sca_results.json || echo '[]') >> full_report.json
          echo ',' >> full_report.json
          echo '"secrets":' >> full_report.json && (cat secrets_found.json || echo '[]') >> full_report.json
          echo ',' >> full_report.json
          echo '"semgrep":' >> full_report.json && (cat semgrep_output.json || echo '[]') >> full_report.json
          echo "}" >> full_report.json

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: scan-results
          path: |
            sast_results.json
            sca_results.json
            secrets_found.json
            semgrep_output.json
            full_report.json

      - name: Count issues per tool
        run: |
          for file in sast_results.json sca_results.json secrets_found.json semgrep_output.json; do
            if [ -s "$file" ]; then
              count=$(jq 'if type=="array" then length elif type=="object" and has("results") then .results | length elif type=="object" then length else 0 end' "$file")
              echo "$file: $count issues"
            else
              echo "$file: 0 issues"
            fi
          done

      - name: Fail if real security issues found
        run: |
          fail=0
          for file in sast_results.json sca_results.json secrets_found.json semgrep_output.json; do
            if [ -s "$file" ]; then
              count=$(jq 'if type=="array" then length elif type=="object" and has("results") then .results | length elif type=="object" then length else 0 end' "$file")
              if [ "$count" -gt 0 ]; then
                echo "Issues detected in $file"
                fail=1
              fi
            fi
          done
          if [ "$fail" -eq 1 ]; then
            exit 1
          fi

  build-and-push:
    needs: security-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.PASS_SECRET }}" | docker login -u "x7m7s7" --password-stdin

      - name: Build Docker Image
        run: docker build -t $IMAGE_TAG .

      - name: Push Docker Image
        run: docker push $IMAGE_TAG

  deploy-staging:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Install Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Deploy with Retry
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --image $IMAGE_TAG --app devops-staging --remote-only --strategy rolling

  nikto-scan:
    needs: deploy-staging
    runs-on: ubuntu-latest
    steps:
      - name: Install Nikto
        run: sudo apt-get update && sudo apt-get install -y nikto

      - name: Run Nikto scan on staging
        run: |
          mkdir -p nikto_reports
          nikto -h http://devops-staging.fly.dev -o nikto_reports/nikto_report.html -Format htm

      - name: Upload Nikto report
        uses: actions/upload-artifact@v4
        with:
          name: nikto-report
          path: nikto_reports/nikto_report.html

  deploy-production:
    needs: nikto-scan
    runs-on: ubuntu-latest
    steps:
      - name: Install Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Deploy to Production on Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN2 }}
        run: flyctl deploy --remote-only --app devops-production -c fly.production.toml
